### ISSUE TITLE
Carousel resets to first page after adding an item

### ISSUE THREAD

**Issue by wcauchois** [theolampert/react-flickity-component#104]
If I add an item to the set of children in my flickity carousel (using this library), and the user has scrolled to a later item, then the carousel resets to the first item (item 0).

Is there any workaround to ensure that the carousel remains on the cell that the user has selected, while adding new items?

Thanks!

**Comment by yaodingyd** [comment]
I'm assuming you are using `reloadOnUpdate`, which essentially reset flickity's state. You have to manually keep track of user's state and use flickity api to restore user's selection.

**Comment by nelsondude** [comment]
@wcauchois Do you recall your solution for this? I'm assuming reloadOnUpdate needs to be false but then what else is required?
