### ISSUE TITLE
wrapAround - First slide always disappears

### ISSUE THREAD

**Issue by MitchEff** [theolampert/react-flickity-component#106]
As soon as the page loads, my left slide is there for half a second, and then disappears. If I change slides, resize my browser etc it comes back, but there's nothing I can do to prevent it from occurring.

<img width="1906" alt="Screen Shot 2020-06-26 at 1 13 17 pm" src="https://user-images.githubusercontent.com/34614502/85816582-17856780-b7af-11ea-80ba-687b95075ee5.png">

Supposed to be this:
<img width="532" alt="Screen Shot 2020-06-26 at 1 15 49 pm" src="https://user-images.githubusercontent.com/34614502/85816612-2ff58200-b7af-11ea-97bf-68ec48dd8418.png">

But it jumps to this after half a second or so:
<img width="550" alt="Screen Shot 2020-06-26 at 1 15 41 pm" src="https://user-images.githubusercontent.com/34614502/85816632-3ab01700-b7af-11ea-93ff-6fbbbeefa5f8.png">

- Doesn't matter how many slides. Does it with 3 slides or 4, 5, 10, etc
- I can remove all my CSS and it still does it
- I can replace all the slide markup with just a span or H1, still does it
- I can remove every option/setting except `wrapAround`, still does it
- Content is certainly not too small for the screen, as you can see it's quite a bit larger

What gives? Has anyone seen this, or know what my options are? I'd really rather not move back to Slick, but I dunno what else to try here. 

There's a staged example [here](https://site.flaim.yourcreative.com.au/environments), if that helps.

**Comment by lil-j** [comment]
This has been happening to me as well.

**Comment by MitchEff** [comment]
Nobody has a solution? I'm gagging to find one - it's affecting all of my sliders...

**Comment by MitchEff** [comment]
Resolved by removing this component and using [this](https://medium.com/yemeksepeti-teknoloji/using-flickity-with-react-a906649b11de).

**Comment by usamecavga** [comment]
I solved this problem by adding **initialIndex: 2** to options.
Hope to help you.
