### ISSUE TITLE
watchCSS option is broken on first render

### ISSUE THREAD

**Issue by mrgnou** [theolampert/react-flickity-component#109]
When `watchCSS` Flickity option is set to `true`, first render will ignore it and flickity carousel will be active instead of staying disabled. Proper behaviour is fixed by resizing the window.

I believe this is because flickity `activate()` [method is called](https://github.com/theolampert/react-flickity-component/blob/master/src/index.js#L45) on `componentDidUpdate()`, even if it has never been activated before.

A possible fix could be to call `activate()` only if it was previously activated before (`this.isActive === true`).

**Comment by juanvisbalco** [comment]
@mrgnou do you have a suggested workaround while the pull request is merged and reviewed? I'm having this same problem.

**Comment by mrgnou** [comment]
@juanvisbalco You can have a look at my fork.
