### ISSUE TITLE
use asNavFor option for server side rendering

### ISSUE THREAD

**Issue by spostad7** [theolampert/react-flickity-component#111]
how can we use external packages like fade and asNavFor?!
I have to slider and want to make asNavFor one for another. how can I achieve this? 
I have installed these packages and using nextjs but it gives 'window is not defined' 

![Annotation 2020-08-03 212914](https://user-images.githubusercontent.com/2351721/89207784-8a64d800-d5d0-11ea-9f8d-1839e84de3dd.png)

**Comment by nboliver** [comment]
@spostad7 you can try something like this: 

```
const fade =
  typeof window !== 'undefined' ? require('flickity-fade') : () => null;

... 

{fade && <Flickity />}
```
