### ISSUE TITLE
`slides` property needs array type definition

### ISSUE THREAD

**Issue by loganstellway** [theolampert/react-flickity-component#112]
## Description

Please excuse me if I have it wrong, but I believe the [`slides` property](https://github.com/theolampert/react-flickity-component/blob/master/src/index.d.ts#L37) should have an [array (`[]`) type definition](https://www.typescriptlang.org/docs/handbook/basic-types.html#array). 

**Setup**
- `react-flickity-component:3.5.0`
- `flickity:2.2.1`
- `typescript`

## Testing

- Create a carousel and set the ref
```
<Flickity flickityRef={(ref) => setCarousel(ref)} {...options} />
```
- In a callback or hook method, log the `Flickity` reference object:
```
const setCarousel = (carousel) => {
  console.log(carousel);
};
```

**Expected Result**
Console will log an object with a `slides` property that is an array. 

-----

This should be a quick fix - once confirmed, I would be happy to create a pull request.

**Comment by theolampert** [comment]
@loganstellway This looks reasonable, feel free to open a PR
