### ISSUE TITLE
flickityRef not working.

### ISSUE THREAD

**Issue by ryanlloydfrench** [theolampert/react-flickity-component#113]
Hi,

My code is set up like the following however I keep getting **_Cannot read property 'flkty' of undefined_**

```
  function myCustomNext() {
    this.flkty.next();
  }
```

```
<Flickity flickityRef={c => this.flkty = c} ></Flickity>
```

How come I cannot access this? Is there a fix?

**Comment by bartosjiri** [comment]
You need to define the `flkty` variable first. 
At the moment, in your `<Flickity>` component you are trying to assign a value to an undefined/non-existing `flkty` variable.


In React v16.8+, you can achieve it by:

```
let flkty = null;

const myCustomNext = () => {
   flkty.next();
};
```
```
<Flickity flickityRef={c => (flkty = c)}>
...
</Flickity>
```
