### ISSUE TITLE
'Module not found, can't resolve 'flickity' with CRA

### ISSUE THREAD

**Issue by majac91** [theolampert/react-flickity-component#119]
Importing Flickity component in a CRA app throws an error:

```Module not found: Can't resolve 'flickity' in '/Users/maja/Desktop/Projects/fiberart-shop/node_modules/react-flickity-component/lib'```

My config: 

<img width="1123" alt="Screenshot 2021-01-25 at 21 25 00" src="https://user-images.githubusercontent.com/62510606/105761767-d0816f80-5f53-11eb-9038-ad70698e0e2c.png">

**Comment by theolampert** [comment]
Hi, you will also need to install flickity itself.

e.g:
```
npm install flickity
```
