### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by andreicek** [theolampert/react-flickity-component#23]
Hi,

from what I see you're packaging whole Flickity with the wrapper and according to their license this falls under [Commercial OEM License](https://flickity.metafizzy.co/license.html#prohibited-uses). You should probably define Flickity as a peer dependency and require users to attach it to the `window` object until Flickity team fixes the issue with requiring the library.

**Comment by yaodingyd** [comment]
Thanks for your concern! Commercial OEM License needs to be "Commercial" first, however this is a open source project. We'll update this project to use GPLv3.

**Comment by andreicek** [comment]
Good catch! Did not think of this!

**Comment by jack-sf** [comment]
But then, this library can't be used in a project, which is not GPL, but paid for Flickity commercial support, am I right?

We'd like to use it, but our project is closed source, so we can't use a library with GPL license.

**Comment by yaodingyd** [comment]
If you get commercial license from the original Flickity project, you are free to use this project in your closed source.

**Comment by kierangillen** [comment]
@yaodingyd @theolampert We really wanted to use this wrapper in our MIT licensed project and we have the commercial Flickity license. However the React Flickity Component explicitly declares GPL3 in the `package.json` https://github.com/theolampert/react-flickity-component/blob/master/package.json#L12 and otherwise only touches on the license in the Readme and in this issue. We are not lawyers but this seems too prone to legal issues without more concrete language in cases using the commercial license. To summarize, we consider our coverage of Flickity to be in accordance with the license but not this package, so we don't feel comfortable using it. Perhaps you could reach out to @desandro, he may have already dealt with similar legal issues and may have some advice on how to properly license it. Thanks for an otherwise perfect package.

**Comment by theolampert** [comment]
@kierangillen I'm also not a lawyer and the licensing issue is a bit murky to me. As you said perhaps @desandro could give us a pointer here.

**Comment by desandro** [comment]
In short, as the owner of  Flickity commercial license, you are okay to use both Flickity and this dependency in both your open and closed source projects.

From a high level, my aim is to allow wide usage of Flickity, but provide some rationale for purchasing a commercial license so I can support development. "Commercial" is in reference to people paying for it, not so much the work they use Flickity for. Technically, the commercial license allows you to use Flickity in closed-source projects. As you own a commercial license, you can include Flickity both in closed and open source projects.

As for the GPL license of this `react-flickity-component` package: the maintainers have decided to adopt GPL as a way of keeping parity between Flickity. The Flickity commercial license terms do not extend to any dependencies so there is some legal gray area. But from a practical standpoint, I'm okay with this usage, and I feel the maintainers of this package will be okay as well. Thanks for checking.

**Comment by yaodingyd** [comment]
Thanks Dave!So the licensing info for this project is accurate. @kierangillen as long as you have commercial license from Flickity, you can use this project in any projects.

**Comment by alloy** [comment]
@yaodingyd @desandro I really understand the spirit and sympathise with trying to be pragmatic, but alas that's not something we can do with legalese 😞. As it stands, this package (`react-flickity-component`) [states it is licensed under GPLv3](https://github.com/theolampert/react-flickity-component/blob/68feb82d5875e6891a93e5041527a931ed518dd7/package.json#L12) and then in a few _other_ locations (such as this issue) mentions are made that “it's ok”, but unfortunately that’s most likely too hand-wavey.

While _you_ may never take action against us, it is important to realise that _others_ may still decide to do so–for instance, a nefarious competitor.

Having said that, perhaps your statements _are_ enough, but in reality [if we really want to respect licenses, which we do] we would have to have a lawyer look at this situation and it would probably be hard for them to come to a conclusion, which means their final answer would likely be “don't take any chances”.

FWIW I _think_ you should be able to eg dual license your code under GPLv3 or MIT, just be sure to inform users that they can only use the MIT license if they have a commercial Flickity license. But then again… IANAL 🤷‍♂
