### ISSUE TITLE
Failed to minify the code ... react-flickity-component/src/index.js:8

### ISSUE THREAD

**Issue by podenphant** [theolampert/react-flickity-component#25]
When invoking 'yarn run build' this error occurs

"Failed to minify the code from this file:

        ./node_modules/react-flickity-component/src/index.js:8
"

**Comment by yaodingyd** [comment]
what kind of minifier you are using? do you have a repo of your configurations?

**Comment by zengoma** [comment]
I'm having the same issue. I used react-create-app to initialize the project and installed flickity using npm. Perhaps this might help (apparently code has to be compiled to ES5 before publishing to npm):
[http://bit.ly/2tRViJ9](http://bit.ly/2tRViJ9)
Hoping that we can solve this without ejecting.

**Comment by yaodingyd** [comment]
@zengoma can you show me the way you import `react-flickity-component`?

**Comment by zengoma** [comment]
@yaodingyd Thank you for the quick response. That certainly did work, the production build runs without any issues now. You're a star!
