### ISSUE TITLE
using with flickity-fullscreen pack?

### ISSUE THREAD

**Issue by repositoryofexcellence** [theolampert/react-flickity-component#38]
Is it possible to use this component with flickity-fullscreen pack?

**Comment by theolampert** [comment]
@repositoryofexcellence yes it's possible.

First you need to install the package:
`npm install flickity-fullscreen`

Then load the css file however you like, for example:
`<link rel="stylesheet" href="https://unpkg.com/flickity-fullscreen@1/fullscreen.css">`

Then enable it in your component, for example:
```js
import Flickity from 'react-flickity-component';
import 'flickity-fullscreen';

class App extends Component {
  render() {

    return (
      <div className="App">
        <Flickity
          className={'carousel'}
          options={{
            fullscreen: true,
          }}
...
```

You still need to style this however, which is covered in the docs here: https://flickity.metafizzy.co/options.html
