### ISSUE TITLE
Type definition

### ISSUE THREAD

**Issue by sjelfull** [theolampert/react-flickity-component#52]
Hey, appreciate this! Makes it very simple to pull in Flickity.

Are you able to add a type definition to this? Flickity [does have one already](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/flickity) - not sure if that makes it any easier.

**Comment by theolampert** [comment]
hey @sjelfull sounds like a good idea 👍 . Would you feel like creating a PR? otherwise I can take a look at this a bit later.

**Comment by theolampert** [comment]
This was added via #54, I'll test today and release a new version.

**Comment by theolampert** [comment]
@tizzle latest (3.2.0) was just published to npm

**Comment by podenphant** [comment]
Hey, 
I could be missing something but the type def doesnt seem to exist?

https://registry.yarnpkg.com/@types%2freact-flickity-component: Not found".
