### ISSUE TITLE
chrome sourcemap warning

### ISSUE THREAD

**Issue by dokko** [theolampert/react-flickity-component#60]
This is not a big deal but after i use this component, in chrome i can see this warning

DevTools failed to parse SourceMap: js/index.js.map

and i dont have index.js in my source..
I know i can turn off Enable Javascript source map in chrome setting but..
can fix this?

**Comment by yaodingyd** [comment]
I'm not even sure what index.js is this. This is not relevant to this library at all. Is it possible it's your application entry file when your bundling tool created? If so you should ask question in webpack/rollup/parcel.

**Comment by yaodingyd** [comment]
@dokko

**Comment by theolampert** [comment]
@yaodingyd I think he's talking about the build sourcemap thats checked into the `lib` folder

**Comment by yaodingyd** [comment]
@theolampert thanks! That makes more sense. @dokko if you can provide your build config I can help take a look.

**Comment by yaodingyd** [comment]
Will reopen with further details.
