### ISSUE TITLE
This doesn't look right. Besides we already have the check in `componentDidMount` lifecycle.

### ISSUE THREAD

**Issue by ebrahimiaval** [theolampert/react-flickity-component#72]
This doesn't look right. Besides we already have the check in `componentDidMount` lifecycle.

_Originally posted by @yaodingyd in https://github.com/theolampert/react-flickity-component/pull/71#issuecomment-508969085_

NO, This is right. in SSR  `componentDidMount`  do not effect JUST 'constructor' and 'render' work.

you must ignore import window dependency plugins  to fix 'window undefined' error. in this commit i ignored flickity to fix it. now we can use in both side.

**Comment by yaodingyd** [comment]
You can comment on the original PR.
