### ISSUE TITLE
Flickity on Firefox not working

### ISSUE THREAD

**Issue by niklasp** [theolampert/react-flickity-component#75]
On Firefox 68.0.2 Flickity is only loading images after the browser window is resized. Tested locally and in the official sandbox https://codesandbox.io/s/qlz12m4oj6. Can anyone confirm? How would I manually trigger a resize Event once the images or the slider is loaded?

![Kapture 2019-08-17 at 16 03 42](https://user-images.githubusercontent.com/1685139/63212694-a42fb580-c108-11e9-88ef-c42367dfee4a.gif)

**Comment by jbsmith731** [comment]
For what it's worth I use a psuedo element with padding bottom. Then absolute position the picture inside of it. https://css-tricks.com/aspect-ratio-boxes/

**Comment by niklasp** [comment]
i dont know the aspect ratio before. all images are different. is there no other solution?

**Comment by yaodingyd** [comment]
Verified. investigating...

**Comment by yaodingyd** [comment]
For the time being you can use `static` to wait for image loaded to resize your carousel

**Comment by niklasp** [comment]
`static` prop also not working for me.

**Comment by theolampert** [comment]
@niklasp please check the latest version (3.4.0), I believe @yaodingyd has fixed this.
