### ISSUE TITLE
Cannot update during an existing state transition

### ISSUE THREAD

**Issue by mlbonniec** [theolampert/react-flickity-component#86]
Hello, small problem with version `3.4.0` of the package. It doesn't seem to impact the rendering, but the error is still present. I didn't find out where this error came from.

---
![Capture d’écran 2019-11-16 à 14 19 49](https://user-images.githubusercontent.com/29955402/68993792-323c4900-087c-11ea-8adc-2648f1fdcf03.png)

**Comment by bhtru** [comment]
I don't know if it's applicable in your use case but setting the `static` prop to `true` removed the error for me.  My carousel contents will be static so it's not issue for me if I can't update the contents on the fly.

On the repo homepage it's mentioned that if you need to update your carousel you can use `reloadOnUpdate`.  That workaround could be worth your time if you absolutely need to remove the error and don't mind the cost.

**Comment by mlbonniec** [comment]
Indeed your solution works, but unfortunately my carousel is dynamic. So I don't know how to fix it.

**Comment by MantasMikal** [comment]
Any news on this?

**Comment by yaodingyd** [comment]
#91 is aimed to fix this

**Comment by TrejoCode** [comment]
Thank you @yaodingyd i will stay waiting for this, because i have the same "error".

**Comment by rockmanvnx6** [comment]
Using `static` and/or `reloadOnUpdate` doesnt work for me. This is how I render it:

```js
 const Posts = edges
        .filter(edge => !!edge.node.frontmatter.date) // You can filter your posts based on some criteria
        .map((edge) => <ShowcaseItem key={edge.node.id} post={edge.node} />)
return  <Flickity options={flickityOptions}>{Posts}</Flickity>
```

**Comment by yaodingyd** [comment]
`3.5.0` is published with the fix. Did you try it out? @rockmanvnx6

**Comment by rockmanvnx6** [comment]
I'm using `3.4.0` due to #96

**Comment by yaodingyd** [comment]
Use the latest version and install your own flickity.

**Comment by yaodingyd** [comment]
@rockmanvnx6 is your issue fixed?

**Comment by rockmanvnx6** [comment]
@yaodingyd sorry was not receiving any notifications on this topic for some reasons, thanks for reminding, will try it out tonight.
