### ISSUE TITLE
Items fixed width not being respected

### ISSUE THREAD

**Issue by guille-alibrate** [theolampert/react-flickity-component#88]
It all works fine in developer mode. But as soon as we build the project, flickity starts to misbehave. See the capture:

![image](https://user-images.githubusercontent.com/56847061/69454299-a4150680-0d44-11ea-93e4-69a0269aec5f.png)

So, images overlaps. Sometimes there are blank spaces. In resume, the items fixed width is not being respected. 

Any clue about why?

We are using nextJs, btw.

**Comment by guille-alibrate** [comment]
This is the expected behavior. This is how it looks in dev mode.

![image](https://user-images.githubusercontent.com/56847061/69454493-138af600-0d45-11ea-8712-ed57240a9092.png)

**Comment by guille-alibrate** [comment]
Oh, one important thing. It's not about images. If we replace the images with a base64 placeholder it still fails. Also, removing the image ad leaving only text has the same effect. So, no clue on what's going on. 

Is there other way to set a fixed width, apart from css? Clearly the math is failing here.

**Comment by yaodingyd** [comment]
Are you sure the width is incorrect? It looks images are in correct width but their position is wrong. As flickity calculates image positions dynamically, it is possible that the calculation happens at the wrong time.

Can you create a minimal sandbox to reproduce your issue? A demo repo will be perfect.

**Comment by yaodingyd** [comment]
Will reopen with sandbox.
