### ISSUE TITLE
flickity carusel no control over margin between images in carusel

### ISSUE THREAD

**Issue by amosguata** [theolampert/react-flickity-component#93]
opened this issue on stackoverflow: 
https://stackoverflow.com/questions/59724659/flickity-carusel-no-control-over-margin-between-images-in-carusel

the problem is i have no control over the the spcae between images in the carusel when resizing the browser window:  [https://codesandbox.io/s/flickity-changin-margin-example-s5gws](url) 

even after adding margin right to each carusel-cel [https://codesandbox.io/s/flickity-changin-margin-example-yk0xj](url) the space between two images is inconsistent after resizing the browser window

before resize:
![before resize](https://user-images.githubusercontent.com/24566211/72319502-f8cf6080-36a7-11ea-8a83-d0100ce77a82.png)

after resize:
![after resize](https://user-images.githubusercontent.com/24566211/72319523-0553b900-36a8-11ea-8458-a5bd27ad969f.png)

**Comment by yaodingyd** [comment]
![Screen Recording 2020-07-14 at 02 17 PM](https://user-images.githubusercontent.com/11392695/87461830-f3ae8800-c5dc-11ea-9448-3f5a22e86cc3.gif)
It works fine for me

**Comment by amosguata** [comment]
@yaodingyd can't you see that the margin is different before resizing window and after? Look closely. 
In your case its a small difference but my hole point is that it is inconsistent.

**Comment by yaodingyd** [comment]
in your example you use `padding-right: 1%;` (not margin) which is not a fixed value so it will shrink after you reduce screen size.

**Comment by amosguata** [comment]
it doesn't really matter if you change the CSS to have margin-right:5px you are still not able to control the margin between images when the windows goes through resize.

before resize:
![image](https://user-images.githubusercontent.com/24566211/88051088-bc058a00-cb60-11ea-84f8-48185753b32e.png)

after resize:
![image](https://user-images.githubusercontent.com/24566211/88051120-c889e280-cb60-11ea-9ffd-2ef91bc82375.png)

**Comment by amosguata** [comment]
when i am saying resize i mean full page and minimizing the browser to be less

**Comment by yaodingyd** [comment]
I can't reproduce ur issue. If you really have `margin:5px` this fixed value not shown by browser, I don't think it's a question for this library.
