### ISSUE TITLE
Focus flickity on mount

### ISSUE THREAD

**Issue by howells** [theolampert/react-flickity-component#97]
Wonder if you could help me out with something - I need to focus flickity on mount (so keyboard nav can be use right away) as per https://codepen.io/desandro/pen/JoemRR but I'm struggling.

```
const flickity = useRef(null);

useEffect(() => {
    if (flickity.current) flickity.current.element.focus();
  }, [flickity.current]);

<Flickity
    className="EntryHeroSlideshow__cells"
    options={flickityOptions}
    flickityRef={c => (flickity.current = c)}
    static
>
    [...]
</Flickity>
```

On page load, `document.activeElement` is the `body` element.

Any ideas where I'm going wrong?

**Comment by nullhook** [comment]
Are you using NextJS?

**Comment by howells** [comment]
@nullhook yes... what do you reckon is up? SSR issue?

**Comment by nullhook** [comment]
It should work if you remove the `static` prop from the `Flickty` component.

When you add `static` prop, it renders the children inside Portal and strangely the focus doesn't work. 

P.S - If you want to keep the `static` prop, delay the focus, it should work. However, I feel adding a `setTimeout` feels hacky.

**Comment by howells** [comment]
@nullhook strange one - I had already removed `static` but it made no difference, but now I've added in a setTimeout it works: hacky but I can't get it to work any other way. Thanks for the suggestion.

**Comment by nullhook** [comment]
Do you have `reloadOnUpdate` prop as true?

**Comment by howells** [comment]
No, these are my props: 

```
<Flickity
            className="EntryHeroSlideshow__cells"
            options={flickityOptions}
            disableImagesLoaded
            flickityRef={c => (flickity.current = c)}
          >
```

and `flickityOptions`:

```
 const flickityOptions = {
    setGallerySize: false,
    prevNextButtons: false,
    lazyLoad: 2,
    pageDots: false,
    autoPlay: duration,
    wrapAround: true,
    pauseAutoPlayOnHover: false,
  };
```

**Comment by nullhook** [comment]
Try removing the disableImagesLoaded prop and see if it works. 

Are you using that prop for something?

**Comment by nullhook** [comment]
Nvm, removing 'static' prop raises other issues such as routing to dynamic pages in NextJS.
