### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by khanbaba** [theolampert/react-flickity-component#98]
Hi,
thanks for this good library.
I need RTL support. Does it support ?

**Comment by TheKingDave** [comment]
Yes Flickity does support RTL

Example:
```jsx
<Flickity
  options={{
    rightToLeft: true,
  }}
>
  <div>1</div>
  <div>2</div>
  <div>3</div>    
</Flickity>
```

You can find further options on the official site of Flickity. https://flickity.metafizzy.co/options.html#righttoleft

**Comment by khanbaba** [comment]
Thanks. That's it.

**Comment by goldylucks** [comment]
Would be easier to find it if it were documented in the readme file :)
